### ISSUE TITLE
Implement HoconTreeTraversingParser#getTokenLocation using ConfigOrigin

### ISSUE THREAD

**Issue by friso** [jclawson/jackson-dataformat-hocon#4]
Currently calling `getTokenLocation()` on a `HoconTreeTraversingParser` object returns `JsonLocation.NA`, which is more or less valid, as there is no JSON location as the input isn't JSON.

Yet for some use cases it does make sense to have access to a location and even the underlying `ConfigOrigin` object. Since the parser has access to this, it would be possible to implement `getTokenLocation()` by returning a subclass of `JsonLocation` that fills the line number field and source object (which are the only things available from `ConfigOrigin`) and provide access to the underlying `ConfigOrigin`.

A concrete use case for this is implementing a custom deserializer for Duration objects using the same code that TypeSafe Config uses for parsing the duration. This requires a `ConfigOrigin`. The custom deserialier could attempt to cast the `JsonLocation` to our own subclass and have access to the origin that way.

I'd be happy to provide a PR that implements this if it is a good idea.

**Comment by jclawson** [comment]
I think this seems good. I'd welcome a pull request that implemented it. Its been a while since I have looked at this code, but I think your subclass of JsonLocation should implement ConfigOrigin. What do you think?

**Comment by friso** [comment]
Ah, you're right. I didn't notice ConfigOrigin is an interface. I'll work on a PR.

**Comment by friso** [comment]
There's a PR for this. Any chance you'll find the time to review and merge?

**Comment by jclawson** [comment]
I will take a look today. And do a release.

**Comment by friso** [comment]
Great! Thanks,
Friso

**Comment by jclawson** [comment]
I just released a new build to maven central.
jackson-dataformat-hocon-1.1.0 should be available there soon.

**Comment by friso** [comment]
It's available now indeed.
Thanks
